In [1]:
cvec = [1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [2]:
rvec = [1 2 3 4 5]

1×5 Matrix{Int64}:
 1  2  3  4  5

In [3]:
mat = [1 2 3; 4 5 6; 7 8 9; 10 11 12]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [4]:
mat2 = [1 2 3
        4 5 6
        7 8 9
        10 11 12]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [5]:
cvec = [1; 2; 3; 4; 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [6]:
[1, 2, 3; 4, 5, 6]

LoadError: syntax: unexpected semicolon in array expression around In[6]:1

In [7]:
ndims(cvec)

1

In [8]:
ndims(rvec)

2

In [9]:
ndims(mat)

2

In [10]:
size(cvec)

(5,)

In [11]:
size(mat)

(4, 3)

In [12]:
size(mat, 1)

4

In [13]:
size(mat, 2)

3

In [14]:
length(mat)

12

In [15]:
mat

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [16]:
mat[2, 3]

6

In [17]:
mat[end, end]

12

In [18]:
mat[3]

7

In [19]:
mat[5]

2

In [20]:
mat[2:4, 2:3]

3×2 Matrix{Int64}:
  5   6
  8   9
 11  12

In [21]:
mat[2, :]

3-element Vector{Int64}:
 4
 5
 6

In [22]:
mat[:, 3]

4-element Vector{Int64}:
  3
  6
  9
 12

In [23]:
cvec1 = [1, 2, 3, 4, 5]
cvec2 = [6, 7, 8, 9, 10]
cvec3 = [11, 12, 13, 14, 15];

In [24]:
vcat(cvec1, cvec2, cvec3)

15-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

In [25]:
hcat(cvec1, cvec2, cvec3)

5×3 Matrix{Int64}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

In [26]:
rvec1 = [1 2 3 4 5]
rvec2 = [6 7 8 9 10]
rvec3 = [11 12 13 14 15];

In [27]:
vcat(rvec1, rvec2, rvec3)

3×5 Matrix{Int64}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

In [28]:
hcat(rvec1, rvec2, rvec3)

1×15 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10  11  12  13  14  15

In [29]:
[cvec1; cvec2; cvec3]

15-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

In [30]:
[cvec1, cvec2, cvec3]

3-element Vector{Vector{Int64}}:
 [1, 2, 3, 4, 5]
 [6, 7, 8, 9, 10]
 [11, 12, 13, 14, 15]

In [31]:
[cvec1 cvec2 cvec3]

5×3 Matrix{Int64}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

In [32]:
[rvec1; rvec2; rvec3]

3×5 Matrix{Int64}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

In [33]:
[rvec1 rvec2 rvec3]

1×15 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10  11  12  13  14  15

In [34]:
m1 = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [35]:
m2 = [11 12 13; 14 15 16]

2×3 Matrix{Int64}:
 11  12  13
 14  15  16

In [36]:
mver = [m1; m2]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
 11  12  13
 14  15  16

In [37]:
mhor = [m1 m2]

2×6 Matrix{Int64}:
 1  2  3  11  12  13
 4  5  6  14  15  16

In [38]:
emptymat = Matrix(undef, 2, 3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [39]:
Matrix{Any}(undef, 2, 3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [41]:
Matrix{Float64}(undef, 3, 2)

3×2 Matrix{Float64}:
 0.0           0.0
 6.93349e-310  6.93348e-310
 6.93349e-310  6.93348e-310

In [42]:
mat = Matrix{Union{Int64, String}}(undef, 3, 4)

3×4 Matrix{Union{Int64, String}}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

In [43]:
mat[2, 3] = 999;
mat[1, 2] = "number";

In [44]:
mat

3×4 Matrix{Union{Int64, String}}:
 #undef     "number"  #undef  #undef
 #undef  #undef       999     #undef
 #undef  #undef       #undef  #undef

In [45]:
mat[3, 4] = 6.78

LoadError: MethodError: Cannot `convert` an object of type 
  Float64 to an object of type 
  Union{Int64, String}
Closest candidates are:
  convert(::Type{T}, ::T) where T at Base.jl:61

In [46]:
nothing

In [47]:
typeof(nothing)

Nothing

In [48]:
Matrix{Any}(nothing, (2, 3))

2×3 Matrix{Any}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [49]:
Matrix{Int64}(nothing, (2, 3))

LoadError: MethodError: Cannot `convert` an object of type Nothing to an object of type Int64
Closest candidates are:
  convert(::Type{T}, ::Ptr) where T<:Integer at pointer.jl:23
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  ...

In [50]:
Matrix{Union{Int64, Nothing}}(nothing, (2, 3))

2×3 Matrix{Union{Nothing, Int64}}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [51]:
missing

missing

In [52]:
typeof(missing)

Missing

In [53]:
Matrix{Union{Missing, String}}(missing, (2, 3))

2×3 Matrix{Union{Missing, String}}:
 missing  missing  missing
 missing  missing  missing

In [54]:
reshape(1:15, 3, 5)

3×5 reshape(::UnitRange{Int64}, 3, 5) with eltype Int64:
 1  4  7  10  13
 2  5  8  11  14
 3  6  9  12  15

In [55]:
reshape(mhor, (4, 3))

4×3 Matrix{Int64}:
 1   3  12
 4   6  15
 2  11  13
 5  14  16

In [56]:
zeros(2, 3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [57]:
ones(2, 3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [58]:
ones(Int32, 2, 3)

2×3 Matrix{Int32}:
 1  1  1
 1  1  1

In [59]:
trues(2, 2)

2×2 BitMatrix:
 1  1
 1  1

In [60]:
falses(2, 2)

2×2 BitMatrix:
 0  0
 0  0

In [61]:
fill(3.14, (3, 2))

3×2 Matrix{Float64}:
 3.14  3.14
 3.14  3.14
 3.14  3.14

In [62]:
rand(1:20, 3, 5)

3×5 Matrix{Int64}:
 12  8  13  12   1
 20  4  18  20  18
  9  9   9   3   2

In [63]:
randn(3, 5)

3×5 Matrix{Float64}:
 -0.295199  0.644578   0.0915864  -0.697282   0.744194
  1.16736   0.26619   -0.193696    0.793127  -0.011854
 -0.959863  0.183289   0.396569    2.58374    1.03099

In [64]:
m1 = reshape(range(12., 23., length=12), (4, 3))

4×3 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 4, 3) with eltype Float64:
 12.0  16.0  20.0
 13.0  17.0  21.0
 14.0  18.0  22.0
 15.0  19.0  23.0

In [65]:
m2 = similar(m1)

4×3 Matrix{Float64}:
 6.93341e-310  6.93341e-310  6.93341e-310
 6.93341e-310  6.93341e-310  6.93341e-310
 6.93341e-310  6.93341e-310  6.93341e-310
 6.93341e-310  6.93341e-310  5.47492e-312

In [66]:
m3 = similar(m1, (3, 3))

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  6.93341e-310