In [2]:
*

* (generic function with 318 methods)

In [3]:
methods(*)

# 318 methods for generic function "*":
[1] *(x::T, y::T) where T<:Union{Int128, UInt128} in Base at int.jl:976
[2] *(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:88
[3] *(x::T, y::T) where T<:Union{Float16, Float32, Float64} in Base at float.jl:385
[4] *(s1::Union{AbstractChar, AbstractString}, ss::Union{AbstractChar, AbstractString}...) in Base at strings/basic.jl:260
[5] *(d::Union{AbstractChar, AbstractString}, x::Missing) in Base at missing.jl:183
[6] *(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigInt) in Base.GMP at gmp.jl:542
[7] *(c::Union{Int16, Int32, Int64, Int8}, x::BigInt) in Base.GMP at gmp.jl:544
[8] *(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:398
[9] *(c::Union{Int16, Int32, Int64, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:406
[10] *(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:414
[11] *(A::StridedMatrix{T}, x::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF32, ComplexF64}, S<:Real} in LinearAlgebra at /julia/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:49
[12] *(A::Union{LinearAlgebra.Adjoint{var"#s886", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s886", <:StridedMatrix{T} where T}, StridedMatrix{var"#s886"}} where var"#s886"<:Union{Float32, Float64}, B::Union{LinearAlgebra.Adjoint{var"#s885", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s885", <:StridedMatrix{T} where T}, StridedMatrix{var"#s885"}} where var"#s885"<:Union{Float32, Float64}) in LinearAlgebra at /julia/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:146
[13] *(A::Union{LinearAlgebra.Adjoint{var"#s886", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s886", <:StridedMatrix{T} where T}, StridedMatrix{var"#s886"}} where var"#s886"<:Union{ComplexF32, ComplexF64}, B::Union{LinearAlgebra.Adjoint{var"#s885", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s885", <:StridedMatrix{T} where T}, StridedMatrix{var"#s885"}} where var"#s885"<:Union{ComplexF32, ComplexF64}) in LinearAlgebra at /julia/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:152
[14] *(A::StridedMatrix{var"#s886"} where var"#s886"<:Union{ComplexF32, ComplexF64}, B::Union{LinearAlgebra.Adjoint{var"#s885", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s885", <:StridedMatrix{T} where T}, StridedMatrix{var"#s885"}} where var"#s885"<:Union{Float32, Float64}) in LinearAlgebra at /julia/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:165
[15] *(A::Union{LinearAlgebra.Adjoint{var"#s886", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s886", <:StridedMatrix{T} where T}} where var"#s886"<:Union{ComplexF32, ComplexF64}, B::Union{LinearAlgebra.Adjoint{var"#s885", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s885", <:StridedMatrix{T} where T}, StridedMatrix{var"#s885"}} where var"#s885"<:Union{Float32, Float64}) in LinearAlgebra at /julia/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:171
[16] *(A::StridedMatrix{var"#s886"} where var"#s886"<:Union{Float32, Float64}, B::StridedMatrix{var"#s885"} where var"#s885"<:Union{ComplexF32, ComplexF64}) in LinearAlgebra at /julia/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:178
[17] *(A::Union{LinearAlgebra.Adjoint{var"#s886", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s886", <:StridedMatrix{T} where T}} where var"#s886"<:Union{Float32, Float64}, B::StridedMatrix{var"#s885"} where var"#s885"<:Union{ComplexF32, ComplexF64}) in LinearAlgebra at /julia/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:185
[18] *(A::Union{LinearAlgebra.Adjoint{var"#s886", <:StridedMatrix{T} where T}, LinearAlgebra.Transpose{var"#s886", <:StridedMatrix{T} where T}, StridedMatrix{var"#s886"}} where var"#s886"<:Union{Float32, Float64}, B::Union{LinearAlgebra.Adjoint{var"#s885", <:StridedMatrix{T} where T}, LinearAlgebr

### Each of the following '*' methods is different.

In [4]:
*(3, 4)

12

In [5]:
*(7.5, 6.6)

49.5

In [6]:
*(4, 6.9)

27.6

In [7]:
mat1 = reshape(Vector(1:12), (3, 4))

3×4 Matrix{Int64}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [8]:
mat2 = reshape(Vector(11:22), (4, 3))

4×3 Matrix{Int64}:
 11  15  19
 12  16  20
 13  17  21
 14  18  22

In [9]:
*(mat1, mat2)

3×3 Matrix{Int64}:
 290  378  466
 340  444  548
 390  510  630

In [10]:
*("Julia", " Programming")

"Julia Programming"

In [11]:
f(x::Float64, y::Float64) = x^2 + y^2

f (generic function with 1 method)

In [12]:
f(3.0, 6.0)

45.0

In [13]:
f(3, 6)

LoadError: MethodError: no method matching f(::Int64, ::Int64)

In [14]:
f(3f0, 6f0)

LoadError: MethodError: no method matching f(::Float32, ::Float32)

In [15]:
f(x::Number, y::Number) = x^2 - y^2

f (generic function with 2 methods)

In [16]:
f(7.0, 4)

33.0

In [17]:
f(8, 6)

28

In [18]:
f(5.6, 9)

-49.64

In [19]:
f(3.0, 4.0)

25.0

In [20]:
f("xyz", 4.5)

LoadError: MethodError: no method matching f(::String, ::Float64)
Closest candidates are:
  f(::Float64, ::Float64) at In[11]:1
  f(::Number, ::Number) at In[15]:1

In [21]:
f

f (generic function with 2 methods)

In [22]:
methods(f)

# 2 methods for generic function "f":
[1] f(x::Float64, y::Float64) in Main at In[11]:1
[2] f(x::Number, y::Number) in Main at In[15]:1

In [23]:
f(x, y) = "I couldn't find the correct method."

f (generic function with 3 methods)

In [24]:
f(x::Any, y::Any) = "I couldn't find the correct method."

f (generic function with 3 methods)

In [25]:
methods(f)

# 3 methods for generic function "f":
[1] f(x::Float64, y::Float64) in Main at In[11]:1
[2] f(x::Number, y::Number) in Main at In[15]:1
[3] f(x, y) in Main at In[24]:1

In [26]:
f("xyz", 5)

"I couldn't find the correct method."

In [27]:
g(x::Int64, y) = x * y

g (generic function with 1 method)

In [28]:
g(x, y::Int64) = x / y

g (generic function with 2 methods)

In [29]:
g(4, 4.5)

18.0

In [30]:
g(4.5, 4)

1.125

In [31]:
g(4, 5)

LoadError: MethodError: g(::Int64, ::Int64) is ambiguous. Candidates:
  g(x::Int64, y) in Main at In[27]:1
  g(x, y::Int64) in Main at In[28]:1
Possible fix, define
  g(::Int64, ::Int64)

In [32]:
g(x::Int64, y::Int64) = x + y

g (generic function with 3 methods)

In [33]:
h(x=3, y=4) = x + y

h (generic function with 3 methods)

In [35]:
h()

7

In [36]:
h(x::Int, y::Int) = x - y

h (generic function with 4 methods)

In [37]:
h()

-1